runtime: python
service: backend
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    operating_system: ubuntu22
    runtime_version: 3.12

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

manual_scaling:
  instances: 1