runtime: python
service: backend
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    operating_system: ubuntu22
    runtime_version: 3.12

manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 20